# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 7fd36e74876c0ab9e01a31adb0bf1c607d1343685c0ff57db94c2b658fb6451a680075f1665eca3c7350d38eaa0a4f1baa879c9f2e3f032af7544b57e1d63c8c

test:
  secret_key_base: 82972aa307a7ab3a4375526deca2065a12cda498ba8ebea46a8d459fdec04bde9798c23693b94a8ca8e5bdbe56b5265196dc836737fc6da0793275bb1772ea4f

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
